import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";
import "@/i18n";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}>
          <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
